#![allow(clippy::type_complexity)]

use std::fmt::Debug;

use avian3d::{collision::CollisionDiagnostics, dynamics::solver::SolverDiagnostics, prelude::*};
use bevy::{prelude::*, scene::ScenePlugin, state::app::StatesPlugin};
use bevy_asset_loader::{
    asset_collection::AssetCollection,
    loading_state::{config::ConfigureLoadingState, LoadingState, LoadingStateAppExt},
};
use godot::classes::{BoxMesh, MeshInstance3D};
use godot_bevy::prelude::{
    godot_prelude::{gdextension, ExtensionLibrary},
    *,
};

#[bevy_app]
fn build_app(app: &mut App) {
    app.add_plugins(AvianPhysicsDemo);
}

struct AvianPhysicsDemo;

#[derive(Debug, Default, Clone, Eq, PartialEq, Hash, States)]
enum GameState {
    #[default]
    LoadAssets,
    InGame,
}

impl Plugin for AvianPhysicsDemo {
    fn build(&self, app: &mut App) {
        app.add_plugins(StatesPlugin)
            .add_plugins((
                // Plugins required by Avian
                ScenePlugin,
                PhysicsPlugins::default(),
            ))
            // The following 4 resource initializations are required by Avian
            .init_resource::<Assets<Mesh>>()
            .init_resource::<CollisionDiagnostics>()
            .init_resource::<SolverDiagnostics>()
            .init_resource::<SpatialQueryDiagnostics>()
            .insert_resource(Gravity::default())
            .init_state::<GameState>()
            .add_loading_state(
                LoadingState::new(GameState::LoadAssets)
                    .load_collection::<GameAssets>()
                    .continue_to_state(GameState::InGame),
            )
            .add_systems(OnExit(GameState::LoadAssets), spawn_entities)
            .add_systems(
                PhysicsUpdate,
                (
                    // TODO: clean up
                    //
                    // print_avian_physics.run_if(in_state(GameState::InGame)),
                    // sync_avian_physics_with_transform.run_if(in_state(GameState::InGame)),
                    // simple_move.run_if(in_state(GameState::InGame)),
                    query_size.run_if(in_state(GameState::InGame)),
                    // print_tree.run_if(in_state(GameState::InGame).and(run_once)),
                ),
            );
    }
}

#[derive(Component)]
pub struct SimpleBoxTag;

#[derive(AssetCollection, Resource, Debug)]
pub struct GameAssets {
    #[asset(path = "scenes/simple_box.tscn")]
    _simple_box_scene: Handle<GodotResource>,

    #[asset(path = "scenes/floor.tscn")]
    floor_scene: Handle<GodotResource>,
}

fn spawn_entities(mut commands: Commands, assets: Res<GameAssets>) {
    //
    // Spawn a static floor
    //
    commands.spawn((
        RigidBody::Static,
        Collider::cuboid(10.0, 0.0, 10.0),
        GodotScene::from_handle(assets.floor_scene.clone()),
    ));

    //
    // Spawn a falling cuboid body with an initial angular velocity
    //
    commands.spawn((
        SimpleBoxTag,
        RigidBody::Dynamic,
        // TODO: it's a chore to have to manually keep the collider dimension values in
        // sync with the Mesh, which is currently in godot's scene. I'm sure we can do
        // better
        Collider::cuboid(1.0, 1.0, 1.0),
        // TODO: pick one of these and remove the other
        GodotScene::from_path("scenes/simple_box.tscn"),
        // GodotScene::from_handle(assets.simple_box_scene.clone()),
        AngularVelocity(Vec3::new(1.0, 2.0, 3.0)),
        // Initialize a bevy transform with the correct starting position so avian's
        // physics simulation is aware of our position. godot-bevy has its own
        // transforms inside of Transform3D, which is generated by GodotScene spawning.
        // We keep avian -> godot-bevy in sync in our `update_system` below
        Transform::default().with_translation(Vec3::new(0., 10., 0.)),
    ));
}

// TODO: use or discard this
fn query_size(
    _commands: Commands,
    mut query: Query<&mut GodotNodeHandle, With<SimpleBoxTag>>,
) -> Result {
    if let Ok(mut godot_node_handle) = query.single_mut() {
        let g = godot_node_handle.get::<MeshInstance3D>();
        let mesh = g.get_mesh().unwrap().cast::<BoxMesh>();
        info!("mesh size: {:?}", mesh.get_size());
    }
    Ok(())
}
