# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "stable"
# The minimal profile includes as few components as possible to get a working
# compiler (rustc, rust-std, and cargo). It’s recommended to use this component
# on Windows systems if you don’t use local documentation (the large number of
# files can cause issues with some Antivirus systems), and in CI.
# The default profile includes all of components in the minimal profile, and
# adds rust-docs, rustfmt, and clippy. This profile will be used by rustup by
# default, and it’s the one recommended for general use.
profile = "default"
components = ["rust-src", "rust-analyzer"]
