import textwrap
from pathlib import Path

from godot_bevy_codegen.src.special_cases import get_type_cfg_attribute
from godot_bevy_codegen.src.gdextension_api import ExtensionApi
from godot_bevy_codegen.src.util import indent_log


def generate_node_markers(
    node_markers_file: Path,
    api: ExtensionApi,
) -> None:
    """Generate the node_markers.rs file"""
    indent_log("🏷️  Generating node markers...")

    content = textwrap.dedent("""\
        use bevy_ecs::component::Component;
        use bevy_ecs::prelude::ReflectComponent;
        use bevy_reflect::Reflect;
        
        /// Marker components for Godot node types.
        /// These enable type-safe ECS queries like: Query<&GodotNodeHandle, With<Sprite2DMarker>>
        ///
        /// 🤖 This file is generated. Changes to it will be lost.
        /// To regenerate: `python -m godot_bevy_codegen`
        
        """)

    # Generate all markers
    node_classes = sorted(api.classes_descended_from("Node"))

    for node_class in node_classes:
        cfg_attr = get_type_cfg_attribute(node_class)
        if cfg_attr:
            content += cfg_attr
        content += f"#[derive(Component, Debug, Clone, Copy, PartialEq, Eq, Default, Reflect)]\n"
        content += f"#[reflect(Component)]\n"
        content += f"pub struct {node_class}Marker;\n\n"

    with open(node_markers_file, "w") as f:
        f.write(content)

    indent_log(f"✅ Generated {len(node_classes)} node markers")


def generate_node_markers_dispatcher(
    output_file: Path,
    versions: list[str],
) -> None:
    """Generate the node_markers.rs file that dispatches to version-specific modules"""
    indent_log("🔌 Generating node markers dispatcher...")

    # Helper to convert "4.2.1" to "4_2_1" for module names and "4-2-1" for feature names
    def format_ver(v: str, sep: str) -> str:
        return v.replace(".", sep)

    latest_version = versions[-1]

    content = textwrap.dedent("""\
        // The Godot versions used here are sourced from Godot-Rust's handling of gdextension API differences:
        // https://github.com/godot-rust/gdext/blob/3f1d543580c1817f1b7fab57a400e82b50085581/godot-bindings/src/import.rs

        // This file is generated by godot_bevy_codegen. Do not edit manually.

        #![allow(unused_imports)]
        #![allow(unexpected_cfgs)]

        """)

    # 1. Module declarations
    for ver in versions:
        content += f'#[cfg(feature = "api-{format_ver(ver, "-")}")]\n'
        content += f'mod node_markers{format_ver(ver, "_")};\n'

    content += "\n"

    # 2. Public re-exports
    for ver in versions:
        content += f'#[cfg(feature = "api-{format_ver(ver, "-")}")]\n'
        content += f'pub use node_markers{format_ver(ver, "_")}::*;\n'

    content += "\n"

    # 3. Default fallback (usually the latest version)
    not_any_conditions = "\n".join(
        [f'    feature = "api-{format_ver(v, "-")}",' for v in versions]
    )
    not_any_conditions += (
        '\n    feature = "api-custom",\n    feature = "api-custom-json",'
    )

    fallback_mod = f"node_markers{format_ver(latest_version, '_')}"

    content += f"#[cfg(not(any(\n{not_any_conditions}\n)))]\n"
    content += f"mod {fallback_mod};\n"
    content += f"#[cfg(not(any(\n{not_any_conditions}\n)))]\n"
    content += f"pub use {fallback_mod}::*;\n"

    with open(output_file, "w") as f:
        f.write(content)

    indent_log(f"✅ Generated node markers dispatcher with {len(versions)} versions")
