import textwrap
from pathlib import Path
from typing import List

from godot_bevy_codegen.src.gdextension_api import ExtensionApi, GodotClass
from godot_bevy_codegen.src.special_cases import (
    SpecialCases,
    get_type_cfg_attribute,
)
from godot_bevy_codegen.src.util import indent_log


def generate_signal_names(
    signal_names_file: Path,
    api: ExtensionApi,
) -> None:
    indent_log("📡 Generating signal names...")

    content = textwrap.dedent("""\
        #![allow(dead_code)]
        //! 🤖 This file is generated. Changes to it will be lost.
        //! To regenerate: uv run python -m godot_bevy_codegen
        //!
        //! Signal name constants for Godot classes.
        //! These provide convenient, discoverable signal names for connecting to Godot signals.
        //!
        //! Example usage:
        //! ```no_run
        //! use godot::classes::Button;
        //! use godot::obj::Gd;
        //! use godot::prelude::Callable;
        //! use godot_bevy::interop::signal_names::BaseButtonSignals;
        //!
        //! fn connect_pressed(button: &mut Gd<Button>, callable: &Callable) {
        //!     button.connect(BaseButtonSignals::PRESSED, callable);
        //! }
        //! ```
        
        """)

    classes_with_signals: List[GodotClass] = [
        c for c in api.classes if c.signals is not None
    ]

    signal_count = 0

    for godot_class in classes_with_signals:
        rust_class_name = SpecialCases.fix_godot_class_name_for_rust(godot_class.name)
        signals_struct_name = f"{rust_class_name}Signals"

        cfg_attr = get_type_cfg_attribute(godot_class.name)
        if cfg_attr:
            content += cfg_attr

        content += f"/// Signal constants for `{rust_class_name}`\n"
        content += f"pub struct {signals_struct_name};\n\n"

        if cfg_attr:
            content += cfg_attr
        content += f"impl {signals_struct_name} {{\n"

        for signal in godot_class.signals:
            signal_name = signal.name
            description = signal.description.strip()
            const_name = _signal_name_to_const(signal_name)

            if description:
                description = _bbcode_to_markdown(description)
                description = _sanitize_doc_comment(description)

                description_lines = description.replace("\r\n", "\n").split("\n")
                for line in description_lines:
                    line = line.rstrip()
                    content += f"    /// {line}\n"
            else:
                content += f"    /// Signal `{signal_name}`\n"

            content += (
                f'    pub const {const_name}: &\'static str = "{signal_name}";\n\n'
            )
            signal_count += 1

        content += "}\n\n"

    with open(signal_names_file, "w") as f:
        f.write(content)

    indent_log(
        f"✅ Generated {signal_count} signal constants across {len(classes_with_signals)} classes"
    )


def generate_signal_names_dispatcher(
    output_file: Path,
    versions: list[str],
) -> None:
    indent_log("🔌 Generating signal names dispatcher...")

    def format_ver(v: str, sep: str) -> str:
        return v.replace(".", sep)

    latest_version = versions[-1]

    content = textwrap.dedent("""\
        // The Godot versions used here are sourced from Godot-Rust's handling of gdextension API differences:
        // https://github.com/godot-rust/gdext/blob/3f1d543580c1817f1b7fab57a400e82b50085581/godot-bindings/src/import.rs

        // This file is generated by godot_bevy_codegen. Do not edit manually.

        #![allow(unused_imports)]
        #![allow(unexpected_cfgs)]

        """)

    for ver in versions:
        content += f'#[cfg(feature = "api-{format_ver(ver, "-")}")]\n'
        content += f'mod signal_names{format_ver(ver, "_")};\n'

    content += "\n"

    for ver in versions:
        content += f'#[cfg(feature = "api-{format_ver(ver, "-")}")]\n'
        content += f'pub use signal_names{format_ver(ver, "_")}::*;\n'

    content += "\n"

    not_any_conditions = "\n".join(
        [f'    feature = "api-{format_ver(v, "-")}",' for v in versions]
    )
    not_any_conditions += (
        '\n    feature = "api-custom",\n    feature = "api-custom-json",'
    )

    fallback_mod = f"signal_names{format_ver(latest_version, '_')}"

    content += f"#[cfg(not(any(\n{not_any_conditions}\n)))]\n"
    content += f"mod {fallback_mod};\n"
    content += f"#[cfg(not(any(\n{not_any_conditions}\n)))]\n"
    content += f"pub use {fallback_mod}::*;\n"

    with open(output_file, "w") as f:
        f.write(content)

    indent_log(f"✅ Generated signal names dispatcher with {len(versions)} versions")


def _signal_name_to_const(signal_name: str) -> str:
    import re

    if not signal_name:
        return "SIGNAL"

    result = re.sub("([a-z0-9])([A-Z])", r"\1_\2", signal_name)

    result = re.sub(r"[^a-zA-Z0-9_]", "_", result)

    result = result.upper()

    result = re.sub(r"_+", "_", result)

    result = result.strip("_")

    if result and result[0].isdigit():
        result = "_" + result

    if not result:
        result = "SIGNAL"

    return result


def _bbcode_to_markdown(text: str) -> str:
    import re
    from textwrap import dedent

    text = text.replace("[b]", "**").replace("[/b]", "**")
    text = text.replace("[i]", "*").replace("[/i]", "*")
    text = text.replace("[code]", "`").replace("[/code]", "`")

    text = re.sub(r"\[member\s+([^]]+)]", r"`\1`", text)

    text = re.sub(r"\[param\s+([^]]+)]", r"`\1`", text)

    text = re.sub(r"\[constant\s+([^]]+)]", r"`\1`", text)

    text = re.sub(r"\[method\s+([^]]+)]", r"`\1()`", text)

    text = re.sub(r"\[signal\s+([^]]+)]", r"`\1`", text)

    text = re.sub(r"\[enum\s+([^]]+)]", r"`\1`", text)

    text = re.sub(r"\[url=([^]]+)]([^\[]+)\[/url]", r"[\2](\1)", text)

    def codeblock_repl(m):
        code = m.group(1).strip()
        code = dedent(code)
        return f"\n```text\n{code}\n```\n"

    text = re.sub(r"\[codeblock](.*?)\[/codeblock]", codeblock_repl, text, flags=re.S)

    def codeblocks_repl(m):
        code = m.group(1).strip()
        code = dedent(code)
        return f"\n```gdscript\n{code}\n```\n"

    text = re.sub(
        r"\[codeblocks](.*?)\[/codeblocks]", codeblocks_repl, text, flags=re.S
    )

    text = re.sub(r"\[/?[a-zA-Z0-9_]+]", "", text)

    return text


def _sanitize_doc_comment(text: str) -> str:
    # Generated API text must not escape its Rustdoc context.

    text = text.replace("\t", "    ")

    text = text.replace("*/", r"*\/")

    text = text.replace("///", r"\/\/\/")

    backtick_count = text.count("`")
    if backtick_count % 2 != 0:
        text += "`"

    return text
