// The Godot versions used here are sourced from Godot-Rust's handling of gdextension API differences:
// https://github.com/godot-rust/gdext/blob/3f1d543580c1817f1b7fab57a400e82b50085581/godot-bindings/src/import.rs

// This file is generated by godot_bevy_codegen. Do not edit manually.

#![allow(unused_imports)]
#![allow(unexpected_cfgs)]

#[cfg(feature = "api-4-2")]
mod signal_names4_2;
#[cfg(feature = "api-4-2-1")]
mod signal_names4_2_1;
#[cfg(feature = "api-4-2-2")]
mod signal_names4_2_2;
#[cfg(feature = "api-4-3")]
mod signal_names4_3;
#[cfg(feature = "api-4-4")]
mod signal_names4_4;
#[cfg(feature = "api-4-5")]
mod signal_names4_5;
#[cfg(feature = "api-4-6")]
mod signal_names4_6;

#[cfg(feature = "api-4-2")]
pub use signal_names4_2::*;
#[cfg(feature = "api-4-2-1")]
pub use signal_names4_2_1::*;
#[cfg(feature = "api-4-2-2")]
pub use signal_names4_2_2::*;
#[cfg(feature = "api-4-3")]
pub use signal_names4_3::*;
#[cfg(feature = "api-4-4")]
pub use signal_names4_4::*;
#[cfg(feature = "api-4-5")]
pub use signal_names4_5::*;
#[cfg(feature = "api-4-6")]
pub use signal_names4_6::*;

#[cfg(not(any(
    feature = "api-4-2",
    feature = "api-4-2-1",
    feature = "api-4-2-2",
    feature = "api-4-3",
    feature = "api-4-4",
    feature = "api-4-5",
    feature = "api-4-6",
    feature = "api-custom",
    feature = "api-custom-json",
)))]
mod signal_names4_6;
#[cfg(not(any(
    feature = "api-4-2",
    feature = "api-4-2-1",
    feature = "api-4-2-2",
    feature = "api-4-3",
    feature = "api-4-4",
    feature = "api-4-5",
    feature = "api-4-6",
    feature = "api-custom",
    feature = "api-custom-json",
)))]
pub use signal_names4_6::*;
