[package]
name = "two-way-sync-example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[[bin]]
path = "../../run_godot.rs"
name = "two_way_sync_example"

[dependencies]
godot-bevy = { path = "../../../godot-bevy" }
godot-bevy-test = { workspace = true, optional = true }
bevy = { version = "0.19", default-features = false }
godot = "0.5"
cargo-godot-lib.workspace = true

[features]
capture = ["dep:godot-bevy-test", "godot-bevy-test/capture"]
itest = []
