//! Auto-sync bundle system for automatic bundle registration
//!
//! `#[derive(GodotNode)]` / `#[derive(BevyComponents)]` registers a bundle-creation
//! function keyed by the type's Godot class. When a node enters the scene tree,
//! the matching creators for the node's class (and its ancestors) are run.

use bevy_app::App;
use bevy_ecs::{entity::Entity, system::Commands, world::World};
use godot::meta::ClassId;
use std::collections::HashMap;
use std::sync::OnceLock;
use tracing::{debug, trace};

use crate::interop::{GodotAccess, GodotNodeHandle};

/// Function type for creating bundles from Godot nodes
pub type BundleCreatorFn = fn(&mut Commands, Entity, &mut GodotAccess, GodotNodeHandle) -> bool;
/// Function type for attaching a Bevy component to a parent entity from a Godot node.
///
/// Returns `true` if the component was successfully attached, `false` otherwise.
pub type AttachComponentFn = fn(&mut Commands, Entity, &mut GodotAccess, GodotNodeHandle) -> bool;

/// Registry entry for auto-sync bundles, constructed only by the derive macros
/// via `inventory::submit!` — `pub` for the macro path, not stable public API.
#[doc(hidden)]
pub struct AutoSyncBundleRegistry {
    /// The bundle struct's name — human-readable, used in trace logs.
    pub godot_class_name: &'static str,
    /// The type's real registered Godot class id (handles `#[class(rename)]`).
    pub godot_class_id_fn: fn() -> ClassId,
    /// Function to create and add the bundle to an entity
    pub create_bundle_fn: BundleCreatorFn,
}

// Collect all auto-sync bundle registrations
crate::inventory::collect!(AutoSyncBundleRegistry);

/// Registry entry for attachable components, constructed only by the derive macros
/// via `inventory::submit!` — `pub` for the macro path, not stable public API.
#[doc(hidden)]
pub struct AttachComponentRegistry {
    /// The Godot class's name — human-readable, used in trace logs.
    pub godot_class_name: &'static str,
    /// The type's real registered Godot class id (handles `#[class(rename)]`).
    pub godot_class_id_fn: fn() -> ClassId,
    /// Function to convert the Godot node and attach the resulting component to the parent entity.
    pub attach_component_fn: AttachComponentFn,
}

crate::inventory::collect!(AttachComponentRegistry);

/// Function type for registering required components generated by `#[gdbevy(require(...))]`.
pub type RequiredComponentsRegistrarFn = fn(&mut World);

/// Registry entry for required-components registration, constructed only by the
/// `GodotNode` derive via `inventory::submit!`.
#[doc(hidden)]
pub struct GodotRequiredComponents {
    pub component_name: &'static str,
    pub registrar_fn: RequiredComponentsRegistrarFn,
}

crate::inventory::collect!(GodotRequiredComponents);

/// Run all required-components registrations on this app's world.
///
/// Must run at plugin build: Bevy requires required-components registration
/// before the target component is ever inserted. Executes per-`App`
/// (registration is per-`World`), so it is NOT `OnceLock`-memoized.
pub fn register_all_required_components(app: &mut App) {
    let world = app.world_mut();
    let mut count = 0;
    for entry in crate::inventory::iter::<GodotRequiredComponents> {
        (entry.registrar_fn)(world);
        trace!(
            "Registered required components for {}",
            entry.component_name
        );
        count += 1;
    }
    debug!("Ran {count} GodotRequiredComponents registrations");
}

// Registered creators keyed by Godot class name, built once at plugin build.
static BUNDLE_REGISTRY: OnceLock<HashMap<String, Vec<&'static AutoSyncBundleRegistry>>> =
    OnceLock::new();

static ATTACH_COMPONENT_REGISTRY: OnceLock<HashMap<String, &'static AttachComponentRegistry>> =
    OnceLock::new();

/// Initialize the global bundle registry, keyed by Godot class name.
pub fn register_all_autosync_bundles(_app: &mut App) {
    BUNDLE_REGISTRY.get_or_init(|| {
        let mut map: HashMap<String, Vec<&'static AutoSyncBundleRegistry>> = HashMap::new();
        for entry in crate::inventory::iter::<AutoSyncBundleRegistry> {
            map.entry((entry.godot_class_id_fn)().to_string())
                .or_default()
                .push(entry);
        }

        tracing::debug!(
            "Registered {} AutoSyncBundle entries across {} Godot classes",
            map.values().map(Vec::len).sum::<usize>(),
            map.len()
        );
        map
    });
}

/// Initialize the global attach component registry, keyed by Godot class name.
///
/// Collects all `AttachComponentRegistry` entries submitted via `inventory::submit!`
/// and stores them in a `HashMap` for fast lookup during scene tree synchronization.
pub fn register_all_attach_components(_app: &mut App) {
    ATTACH_COMPONENT_REGISTRY.get_or_init(|| {
        let mut map: HashMap<String, &'static AttachComponentRegistry> = HashMap::new();
        for entry in crate::inventory::iter::<AttachComponentRegistry> {
            map.entry((entry.godot_class_id_fn)().to_string())
                .or_insert(entry);
        }

        tracing::debug!("Registered {} AttachComponent entries", map.len());
        map
    });
}

/// Add registered bundles for a node, matched by its Godot class hierarchy.
///
/// `class_hierarchy` is the node's class followed by its ancestors (as produced
/// by the scene-tree plugin). A registered type matches iff its class name is in
/// that chain — i.e. the node is-a that type. The matched `create_bundle_fn`
/// still does a `try_get` to retrieve the typed node it builds the bundle from.
pub(crate) fn try_add_bundles_for_node(
    commands: &mut Commands,
    entity: Entity,
    godot: &mut GodotAccess,
    node_handle: GodotNodeHandle,
    class_hierarchy: &[String],
) {
    let Some(registry) = BUNDLE_REGISTRY.get() else {
        return;
    };
    for class_name in class_hierarchy {
        let Some(entries) = registry.get(class_name) else {
            continue;
        };
        for entry in entries {
            if (entry.create_bundle_fn)(commands, entity, godot, node_handle) {
                trace!(
                    "Added bundle for {} to entity {:?}",
                    entry.godot_class_name, entity
                );
            }
        }
    }
}

/// Attempt to attach a Bevy component to the given parent entity from a Godot node.
///
/// Looks up the node's `class_name` in the attach component registry. If a matching
/// entry is found, it executes the registered `attach_component_fn` to convert the
/// Godot node into a Bevy component and insert it into the parent entity.
///
/// Returns `true` if a component was successfully attached, `false` otherwise.
pub(crate) fn try_attach_component_to_parent(
    commands: &mut Commands,
    parent: Entity,
    godot: &mut GodotAccess,
    node_handle: GodotNodeHandle,
    class_name: &str,
) -> bool {
    let Some(registry) = ATTACH_COMPONENT_REGISTRY.get() else {
        return false;
    };

    let Some(entry) = registry.get(class_name) else {
        return false;
    };

    if (entry.attach_component_fn)(commands, parent, godot, node_handle) {
        trace!(
            "Attached component {} to entity {:?}",
            entry.godot_class_name, parent
        );
        return true;
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_app::App;
    use bevy_ecs::prelude::Component;

    #[derive(Component)]
    struct Primary;
    #[derive(Component, PartialEq, Debug, Default)]
    struct Companion(u8);

    fn register_primary(world: &mut World) {
        let _ = world.try_register_required_components_with::<Primary, Companion>(|| Companion(7));
    }
    crate::inventory::submit! {
        GodotRequiredComponents { component_name: "Primary", registrar_fn: register_primary }
    }

    #[test]
    fn registrar_entries_apply_to_new_world() {
        let mut app = App::new();
        register_all_required_components(&mut app);
        let e = app.world_mut().spawn(Primary).id();
        assert_eq!(app.world().get::<Companion>(e), Some(&Companion(7)));
    }
}
