[book]
authors = ["David Chavez"]
language = "en"
multilingual = false
src = "src"
title = "The godot-bevy Book 👾"

[output.html]
git-repository-url = "https://github.com/bytemeadow/godot-bevy"
edit-url-template = "https://github.com/bytemeadow/godot-bevy/edit/main/book/{path}"
fold.enable = true
fold.level = 1
