name: benchmark-baseline

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write

jobs:
  commit-baseline:
    name: Commit benchmark baseline
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_PAT || secrets.GITHUB_TOKEN }}

      - name: Download benchmark artifacts
        id: download
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: benchmark-results
          path: benchmark-artifacts/

      - name: Check for baseline file
        id: check
        run: |
          # Check if artifacts were downloaded successfully
          if [ "${{ steps.download.outcome }}" != "success" ]; then
            echo "found=false" >> $GITHUB_OUTPUT
            echo "📋 No benchmark artifacts found (CI may not have run benchmarks)"
            exit 0
          fi
          
          # Check if CI generated a baseline file
          if [ -f "benchmark-artifacts/examples/perf-test/baseline.json" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "✅ Found baseline.json in artifacts"
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "📋 No baseline.json found in artifacts"
            # Debug: list what's in the artifacts
            echo "Contents of benchmark-artifacts:"
            find benchmark-artifacts -type f -name "*.json" || true
          fi

      - name: Update baseline
        if: steps.check.outputs.found == 'true'
        run: |
          # Copy baseline to the correct location
          cp benchmark-artifacts/examples/perf-test/baseline.json examples/perf-test/baseline.json
          
          # Add CI metadata
          jq '. + {"ci_metadata": {"commit": "${{ github.event.workflow_run.head_sha }}", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "runner": "GitHub Actions"}}' \
            examples/perf-test/baseline.json > baseline.tmp.json
          mv baseline.tmp.json examples/perf-test/baseline.json

      - name: Commit and push
        if: steps.check.outputs.found == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add -f examples/perf-test/baseline.json
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "📋 No changes to baseline.json"
          else
            git commit -m "chore: update benchmark baseline from CI [skip ci]

          Updated baseline from commit: ${{ github.event.workflow_run.head_sha }}
          Runner: GitHub Actions

          This ensures all benchmarks are compared against a consistent baseline from the same hardware."

            git push origin main
            echo "✅ Pushed updated baseline to main"
          fi